stage:
  global:
    SKIP_HTML_MINIFICATION: true
    X_FRAME_CONFIGURATION: SAMEORIGIN
  build:
    SCD_THREADS: 4
    SCD_COMPRESSION_LEVEL: 8
    SCD_MATRIX:
      "magento/backend":
        language:
          - en_US
          - pt_BR
      "magento/Luma":
        language:
          - en_US
          - pt_BR
  deploy:
    SCD_STRATEGY: "standard"
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    SEARCH_CONFIGURATION:
      _merge: true
      engine: ElasticSuite
      ELASTICSUITE_CONFIGURATION:
        _merge: true
        es_client:
          servers: 'opensearch:9200'
        indices_settings:
          number_of_shards: 1
          number_of_replicas: 1
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers:
        - product_action_attribute.update
        - product_action_attribute.website.update
        - media.storage.catalog.image.resize
        - matchCustomerSegmentProcessor
        - codegeneratorProcessor
        - negotiableQuotePriceUpdate
        - exportProcessor
        - sharedCatalogUpdatePrice
        - sharedCatalogUpdateCategoryPermissions
        - inventory.source.items.cleanup
        - inventory.mass.update
        - inventory.reservations.cleanup
        - inventory.reservations.update
        - purchaseorder.toorder
        - purchaseorder.transactional.email
        - purchaseorder.validation
        - quoteItemCleaner
        - inventoryQtyCounter
        - inventory.reservations.updateSalabilityStatus
        - inventory.indexer.sourceItem
        - inventory.indexer.stock
        - media.content.synchronization
        - media.gallery.renditions.update
        - media.gallery.synchronization
        - async.operations.all
