mysql:
  type: mariadb:10.6
  disk: 2048

redis:
  type: redis:7.0

opensearch:
  type: opensearch:2.4
  disk: 1024
  configuration:
    plugins:
      - analysis-icu
      - analysis-phonetic

rabbitmq:
  type: rabbitmq:3.9
  disk: 512
